config/routes.rb
Cookbook::Application.routes.draw do
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  root to: 'recipes#index'

  resources :users
  resources :sessions
  resources :friendships
  resources :activities
  resources :recipes do
    resources :comments
  end
end

app/models/activity.rb
class Activity < ActiveRecord::Base
  belongs_to :user
  belongs_to :trackable, polymorphic: true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :recipe
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, class_name: "User"
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  belongs_to :user
  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  
  validates_uniqueness_of :name

  has_many :activities
  has_many :recipes
  has_many :comments
  has_many :friendships
  has_many :friends, through: :friendships
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController

	def index
		@activities = Activity.order("created_at desc")
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def require_login
    redirect_to login_url, alert: "You must first log in or sign up." if current_user.nil?
  end

  def track_activity(trackable, action = params[:action])
  	current_user.activities.create! action: action, trackable: trackable	
  end
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_login
  before_action :load_recipe

  def create
    @comment = @recipe.comments.build(comment_params)
    @comment.user = current_user
    if @comment.save
     track_activity @comment
     redirect_to @recipe, notice: "Comment was created."
    else
      render :new
    end
  end

  def edit
    @comment = current_user.comments.find(params[:id])
  end

  def update
    @comment = current_user.comments.find(params[:id])
    if @comment.update_attributes(comment_params)
      track_activity @comment
      redirect_to @recipe, notice: "Comment was updated."
    else
      render :edit
    end
  end

  def destroy
    @comment = current_user.comments.find(params[:id])
    @comment.destroy
    track_activity @comment
    redirect_to @recipe, notice: "Comment was destroyed."
  end

private
  def comment_params
    params.require(:comment).permit(:content)
  end

  def load_recipe
    @recipe = Recipe.find(params[:recipe_id])
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  before_action :require_login

  def create
    @friendship = current_user.friendships.create!(:friend_id => params[:friend_id])
    redirect_to :back, notice: "Added friend."
  end

  def destroy
    @friendship = current_user.friendships.find(params[:id])
    @friendship.destroy
    redirect_to :back, notice: "Removed friendship."
  end

  private
  def comment_params
    params.require(:friendship).permit(:friend_id)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :require_login, except: [:index, :show]

  def index
    @recipes = Recipe.all
  end

  def show
    @recipe = Recipe.find(params[:id])
    @comment = Comment.new
  end

  def new
    @recipe = current_user.recipes.build
  end

  def create
    @recipe = current_user.recipes.build(recipe_params)
    if @recipe.save
      track_activity @recipe
      current_user.activities.redirect_to @recipe, notice: "Recipe was created."
    else
      render :new
    end
  end

  def edit
    @recipe = current_user.recipes.find(params[:id])
  end

  def update
    @recipe = current_user.recipes.find(params[:id])
    if @recipe.update_attributes(recipe_params)
      track_activity @recipe
      redirect_to @recipe, notice: "Recipe was updated."
    else
      render :edit
    end
  end

  def destroy
    @recipe = current_user.recipes.find(params[:id])
    @recipe.destroy
    track_activity @recipe
    redirect_to recipes_url, notice: "Recipe was destroyed."
  end

  private
  def recipe_params
    params.require(:recipe).permit(:description, :image_url, :name)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_name(params[:name])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logged in!"
    else
      flash.now.alert = "Name or password is invalid"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: "Thank you for signing up!"
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private
  def user_params
    params.require(:user).permit(:name, :password, :password_confirmation)
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/activities/comment/_create.html.erb
commented on <%= link_to comment.recipe.name, comment.recipe %>

app/views/activities/comment/_destroy.html.erb
deleted a comment

app/views/activities/index.html.erb
<h1>Activities</h1>

<% @activities.each do |activity| %>
  <%= ActivityPresenter.new(activity, self).render_activity %>
<% end %>

app/views/comments/_comment.html.erb
<%= div_for comment do %>
  <p><strong><%= link_to comment.user.name, comment.user %> says</strong></p>
  <%= simple_format comment.content %>
  <% if comment.user == current_user %>
    <p>
      <%= link_to "Edit", edit_recipe_comment_path(@recipe, comment) %> |
      <%= link_to "Destroy", [@recipe, comment], method: :delete %>
    </p>
  <% end %>
<% end %>

app/views/comments/_form.html.erb
<%= form_for [@recipe, @comment] do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>
      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_area :content, rows: 8, cols: 30 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Edit Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', @recipe %>

app/views/comments/new.html.erb
<h1>Post Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', @recipe %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cookbook</title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tag %>
  </head>
  <body>
    <div id="container">
      <div id="user_nav">
        <% if current_user %>
          Logged in as <%= current_user.name %>.
          <%= link_to "Log Out", logout_path %>
        <% else %>
          <%= link_to "Sign Up", signup_path %> or
          <%= link_to "Log In", login_path %>
        <% end %>
      </div>

      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, id: "flash_#{name}" %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/recipes/_form.html.erb
<%= form_for(@recipe) do |f| %>
  <% if @recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% @recipe.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br />
    <%= f.text_field :image_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/recipes/_recipe.html.erb
<%= div_for recipe do %>
  <%= image_tag recipe.image_url, size: "120x120" %>
  <h2><%= link_to_unless_current recipe.name, recipe %></h2>
  <%= simple_format recipe.description %>
  <em>added by <%= link_to recipe.user.name, recipe.user %></em>
<% end %>

app/views/recipes/edit.html.erb
<h1>Editing recipe</h1>

<%= render 'form' %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<h1>Recipes</h1>

<%= render @recipes %>

<p><%= link_to "New Recipe", new_recipe_path %></p>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= render 'form' %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/show.html.erb
<%= render @recipe %>

<%= link_to "Back to Recipes", recipes_path %>
<% if @recipe.user == current_user %>
  | <%= link_to "Edit Recipe", edit_recipe_path(@recipe) %>
  | <%= link_to "Destroy Recipe", @recipe, method: :delete %>
<% end %>

<h2>Comments</h2>

<div id="comments">
  <%= render @recipe.comments %>
</div>

<h3>New Comment</h3>

<%= render 'comments/form' %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit "Sign Up" %></div>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %>'s Profile</h1>

<% if current_user && current_user != @user %>
  <% if current_user.friends.include? @user %>
    <%= link_to "Remove Friend", current_user.friendships.find_by_friend_id(@user.id), method: :delete %>
  <% else %>
    <%= link_to "Add Friend", friendships_path(friend_id: @user), method: :post %>
  <% end %>
<% end %>

<h2>Recipes</h2>

<%= render @user.recipes %>